import Head from "next/head";
import Image from "next/image";

import Footer from "../components/Footer";
import Hero from "../components/Hero";

import Navbar from "../components/Navbar";

import Values from "../components/Values";
import { useSession } from "next-auth/react";

export default function Home() {
  const {data:session}=useSession()
  return (
    <div>
      <Head>
        <title>SOS Mate</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session ? User(session):Guest()}
    </div>
  );
}

function User(session){
  return(
    <div>
    <Hero/>
    <Values/>
    <Footer/>
    </div>
  )
}

function Guest(){
  return(
    <div>
      <p>Empty page</p>
    </div>
  )
}
